// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAak1Xn9NM0rhhmLsLT7FOxdHSbzrJcK0',
    appId: '1:788734188363:web:9a8c2c8f89f4554bdda6ce',
    messagingSenderId: '788734188363',
    projectId: 'saisunsatsuei-950cf',
    authDomain: 'saisunsatsuei-950cf.firebaseapp.com',
    storageBucket: 'saisunsatsuei-950cf.firebasestorage.app',
    measurementId: 'G-S94RCKLC4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwX78eJSDWS6Jat8yx-w3lh8IFS3Xyb08',
    appId: '1:788734188363:android:ac1412c0b47a6cdfdda6ce',
    messagingSenderId: '788734188363',
    projectId: 'saisunsatsuei-950cf',
    authDomain: 'saisunsatsuei-950cf.firebaseapp.com',
    storageBucket: 'saisunsatsuei-950cf.firebasestorage.app',
  );
}
